#!/bin/bash

# Link to the binary
ln -sf '/opt/Joplin/joplin' '/usr/bin/joplin'

# ensure proper permissions
chmod -R 755 '/opt/Joplin' || true

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/Joplin/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
