#!/bin/bash

# Link to the binary
ln -sf '/usr/lib/joplin' '/usr/bin/joplin'

# ensure proper permissions

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/usr/lib/joplin/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
